### ISSUE TITLE
BOSS - Zerg build order simulation does not work correctly

### ISSUE THREAD

**Issue by davechurchill** [davechurchill/ualbertabot#2]
This is a long-standing issue. Please add support for zerg build orders

**Comment by JDongian** [comment]
Is this still in issue? The comment on your [youtube video](https://www.youtube.com/watch?v=0qcR86OVw8Q) seems to suggest otherwise.

**Comment by davechurchill** [comment]
Yes it is, not everything is integrated I to the not properly yet
