### ISSUE TITLE
BOSS and SparCraft output paths

### ISSUE THREAD

**Issue by kmichaelfox** [davechurchill/ualbertabot#27]
The output path for the Boss currently is set to the bin directory of its project. This breaks compilation of the main bot without copy and pasting the libs. Maybe a post build step could put the libs for both SparCraft and BOSS in both places (_`<Project>`/bin_ as well as _UalbertaBot/VisualStudio/`<Debug or Release>`/bin_), or the linker paths for UAlbertaBot should be changed to look in the bin dir.

Or maybe I'm just missing something... Apologies if so.

**Comment by davechurchill** [comment]
Thanks for the heads up. I changed the paths recently without checking out
it affected the bot. I will fix this soon

On Thu, May 5, 2016 at 8:02 PM, K. Michael Fox notifications@github.com
wrote:

> The output path for these two projects currently is set to the bin
> directory of the respective projects. This breaks compilation of the main
> box without copy and pasting the libs. Maybe a post build step could put
> the libs in both places, or the link paths for UAlbertaBot should be
> changed to look in the bin dir.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/davechurchill/ualbertabot/issues/27

## 

David Churchill - dave.churchill@gmail.com

PhD Student, Artificial Intelligence
Computing Science Department, University of Alberta
http://webdocs.cs.ualberta.ca/~cdavid/ cdavid@cs.ualberta.ca

Lead AI Programmer, Lunarch Studios
http://www.lunarchstudios.com/ http://lunarchstudios.com/

**Comment by davechurchill** [comment]
Fixed. Changed UAlbertaBot project to link to relative path to BOSS/bin/BOSS.lib for linking
