### ISSUE TITLE
Problem compiling error C2064: term does not evaluate to a function taking 0 arguments

### ISSUE THREAD

**Issue by Feartheway** [davechurchill/ualbertabot#30]
i got rid of the spaces,  in starcraft ai dir to become starcraftai dir.
I sorted out boost being in a nested directory  ... 

now i get this?

AllPlayers.cpp
e:\starcraftai\ualbertabot_aiide_2013_2014\ualbertabot\src\ualbertabot_aiide_2013_source_full\sparcraft\source\Position.hpp(31): error C2064: term does not evaluate to a function taking 0 arguments

**Comment by davechurchill** [comment]
Not gonna spend any more time on this because I'll be releasing a big
update soon.

**Comment by Feartheway** [comment]
nps,
