### ISSUE TITLE
Meet attempting to reference deleted function 

### ISSUE THREAD

**Issue by cumttang** [davechurchill/ualbertabot#32]
When I try to compile the project in visual studio 2015， I met the problem that attempting to reference deleted function. 
Error C2280 “BWAPI::Unitset &BWAPI::Unitset::operator =(const BWAPI::Unitset &)”: 	attempt to reference deleted function UAlbertaBot	F:\0.starcraft\Basic\ualbertabot\UAlbertaBot\source\MicroManager.cpp

What's wrong with the codes? Please help!

**Comment by davechurchill** [comment]
The project should be compiled in VS2013

**Comment by cumttang** [comment]
I have used vs2013, however, UAlbertaBot.dll can not be loaded in the correct path way without spaces. What's wrong with it?

**Comment by davechurchill** [comment]
I can assure you that the instructions work correctly. Try watching the
video again? It's hard to tell what's wrong without being there. Directory
typos or spaces are the number one issue usually.

It WILL NOT work with vs2015

**Comment by cumttang** [comment]
Additionally, it can be used in win7, however, UAlbertaBot.dll can not be loaded in win10 64-bits.

**Comment by davechurchill** [comment]
Yes it can. I use it last week in win10.

You probably need to change chaos launcher and StarCraft to be run in
administrator mode.

Trust me, it all works :)

**Comment by cumttang** [comment]
Sorry to bother you, but when I used win 7 to run the dll in the auto menu, it always takes about 1 minutes stop it. And then work, is there anything like loaded in this process? 
 And when I used single game by hand click, it runs immediately.

**Comment by davechurchill** [comment]
I can tell you haven't watched the video because all this is explained.
Please watch it again. Closing this issue now

**Comment by xdhmoore** [comment]
I am currently running the master branch on win7 successfully.
