### ISSUE TITLE
1.16.1 patch no longer available at URL in installation instructions

### ISSUE THREAD

**Issue by honzi** [davechurchill/ualbertabot#35]
The link given in step 1 of the [Installation Instructions](https://github.com/davechurchill/ualbertabot/wiki/Installation-Instructions#how-to-run) for upgrading to version 1.16.1 no longer contains that specific patch available for download. The user is instead linked to the full download of StarCraft, which installs the most recent version (1.18.x at the moment).

According to https://github.com/bwapi/bwapi/issues/710 1.18.x "won't be supported for some time", so this installation step should be changed.

**Comment by xdhmoore** [comment]
I think there is still an official Blizzard page somewhere with that download, but I don't remember where it is. I think I remember getting it from them and not a random forum.

**Comment by richoux** [comment]
Hi all, I just uploaded the 1.16.1 patch on my web server: http://richoux.fr/files/BW-1161.exe
Cheers,
Flo

**Comment by xdhmoore** [comment]
FWIW, the hashes for my copy are:

MD5       b20bfe9c4393c0479418d2d9b0402cdb
SHA1      cb650fcad509fd0ce83979e89c61874bf027b8a4
SHA256  96890f59b664eb54dbb3be634f2045e70a4a757e87b405ec4aeeb69d50fb7bb1

**Comment by xdhmoore** [comment]
I managed to track down a link and updated the instructions.

http://ftp.blizzard.com/pub/broodwar/patches/PC/BW-1161.exe

This is where I found the reference. It looks like someone has set up a mirror as well:
https://bnetdocs.org/news/118/starcraft-patch-1-17-0-pre-release
