### ISSUE TITLE
Andromeda map analysis fails

### ISSUE THREAD

**Issue by bftjoe** [davechurchill/ualbertabot#37]
In the sparcraft_update branch, UAB is unable to find any expansions on Andromeda.

Andromeda has the closest natural minerals to main base out of all the SSCAIT maps, which could be a factor.

**Comment by bftjoe** [comment]
Nevermind, this was caused by failing to restart the client in between games.

**Comment by davechurchill** [comment]
This branch is currently not stable, please don't open issues for it :)
