### ISSUE TITLE
which version of visual studio and BWAPI ?

### ISSUE THREAD

**Issue by topdavidwu** [davechurchill/ualbertabot#38]
which version of visual studio can be used to compile  UAlbertaBot_AIIDE_2013_2014.zip correctlly?
which version of BWAPI for it?

**Comment by davechurchill** [comment]
2012 and 374  I think

**Comment by topdavidwu** [comment]
thank you! I try to compile it.

**Comment by topdavidwu** [comment]
but BWAPI::WalkPosition and BWAPI::Unitset is not in bwapi3.7.4

**Comment by topdavidwu** [comment]
could you tell me the specific version of visual studio, bwapi and bwta for  UAlbertaBot_AIIDE_2013_2014?

**Comment by topdavidwu** [comment]
When I compiling bwapi3.7.4, the error is as follows:

1>  Position.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector(1855): error C2825: '_Alloc': must be a class or namespace when followed by '::'
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector(1907) : see reference to class template instantiation 'std::_Vb_iter_base<_Alloc>' being compiled
1>          with
1>          [
1>              _Alloc=unsigned int
1>          ]
1>          source\BW\Position.cpp(62) : see reference to class template instantiation 'std::_Vb_reference<unsigned int>' being compiled
1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector(1855): error C2039: 'difference_type' : is not a member of '`global namespace''
1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector(1855): error C2146: syntax error : missing ',' before identifier 'difference_type'
1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector(1855): error C2065: 'difference_type' : undeclared identifier
1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector(1858): error C2977: 'std::_Iterator012' : too many template arguments
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xutility(354) : see declaration of 'std::_Iterator012'
1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector(1859): error C2955: 'std::_Iterator012' : use of class template requires template argument list
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xutility(354) : see declaration of 'std::_Iterator012'
1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector(1861): error C2825: '_Alloc': must be a class or namespace when followed by '::'
1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector(1861): error C2039: 'size_type' : is not a member of '`global namespace''
1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector(1861): error C2146: syntax error : missing ';' before identifier '_Sizet'
1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector(1869): error C2061: syntax error : identifier '_Sizet'
1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector(1876): error C2061: syntax error : identifier '_Sizet'
1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector(1883): error C2061: syntax error : identifier '_Sizet'
1>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector(1900): error C2146: syntax error : missing ';' before identifier '_Myoff'

what's happen? How to fix the error?

**Comment by davechurchill** [comment]
Then it's probably 4.1.2? I'm not sure.

Why do you need to compile old versions of the bot? The dlls are provided

**Comment by topdavidwu** [comment]
Because the bwapi.dll of bwapi4.1.2 version seems to conflict with your UAlbertaBot.dll.

I encountered the following error：
https://github.com/bwapi/bwapi/issues/732

**Comment by davechurchill** [comment]
Ok. As those versions are no longer supported, I am going to close this ticket. You'll have to experiment with them.
