### ISSUE TITLE
How can I apply ai?

### ISSUE THREAD

**Issue by haejin315** [davechurchill/ualbertabot#48]
I downloaded the ai from here.  (   https://www.cs.mun.ca/~dchurchill/starcraftaicomp/2021/bots/   )
UAIBertaBot using the exe file, but the other AI's are dll files.

Another problem is
Starts with replay and ends immediately.
How can I start UAIBertabot with a replay?

**Comment by davechurchill** [comment]
https://www.youtube.com/watch?v=Bw2IDR5gt7c

**Comment by davechurchill** [comment]
You can't, it's not designed to. It's designed to play the game not analyze replays

**Comment by davechurchill** [comment]
https://www.youtube.com/watch?v=Bw2IDR5gt7c
