### ISSUE TITLE
Zealot v.s. Zergling

### ISSUE THREAD

**Issue by ghost** [davechurchill/ualbertabot#6]
In UAlbertaBot/Source/CombatSimulation.cpp line 105:

if (onlyZerglings && (numZealots*3 > numZerglings))

I think you mean numZealots > numZerglings*3, right? :P

**Comment by jchildren** [comment]
I've only looked briefly at the code, but the purpose of the function seems to be to determine whether your zealots would win versus the enemy zerglings and return a bool?

For your zealot to win you need to be fighting less than three lings, so the function should return true in that case. The line of code mentioned satisfies that condition as if three times your number of zealots is greater than the number of lings you are likely to win the engagement.

**Comment by davechurchill** [comment]
There is more than just this issue with the code, it actually isn't even being called correctly from the outside, I will fix it when I have a bit more time :)
